// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_event_ from "./routes/[event].tsx";
import * as $_event_submissions from "./routes/[event]/submissions.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $pages_page_ from "./routes/pages/[page].tsx";
import * as $user_user_ from "./routes/user/[user].tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[event].tsx": $_event_,
    "./routes/[event]/submissions.tsx": $_event_submissions,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/pages/[page].tsx": $pages_page_,
    "./routes/user/[user].tsx": $user_user_,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
